-- Create code_snapshots table for historical code snapshots
-- This table stores snapshots when code is executed, saved, or added to AI context
-- The main 'code' table remains as live, auto-saved storage

create table public.code_snapshots (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid(),
  timestamp timestamp with time zone not null default now(),
  code_id bigint not null,
  session_id bigint not null,
  content text null default ''::text,
  save_source text not null,
  constraint code_snapshots_pkey primary key (id),
  constraint code_snapshots_code_id_fkey foreign key (code_id) references code (id) on update cascade on delete cascade,
  constraint code_snapshots_session_id_fkey foreign key (session_id) references sessions (id) on update cascade on delete restrict,
  constraint code_snapshots_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete restrict
) tablespace pg_default;

-- Create index for faster queries by code_id
create index idx_code_snapshots_code_id on public.code_snapshots (code_id);

-- Create index for faster queries by session_id
create index idx_code_snapshots_session_id on public.code_snapshots (session_id);

-- Create index for faster queries by timestamp
create index idx_code_snapshots_timestamp on public.code_snapshots (timestamp desc);

-- Enable Row Level Security
alter table public.code_snapshots enable row level security;

-- Policy: Users can only view their own code snapshots
create policy "Users can view their own code snapshots"
  on public.code_snapshots
  for select
  using (auth.uid() = user_id);

-- Policy: Users can create their own code snapshots
create policy "Users can create their own code snapshots"
  on public.code_snapshots
  for insert
  with check (auth.uid() = user_id);

-- Policy: Users can delete their own code snapshots (optional - for cleanup)
create policy "Users can delete their own code snapshots"
  on public.code_snapshots
  for delete
  using (auth.uid() = user_id);

-- Add comment to table
comment on table public.code_snapshots is 'Historical snapshots of code taken at significant events (run, save, AI context)';

-- Add comments to columns
comment on column public.code_snapshots.code_id is 'Reference to the parent code record';
comment on column public.code_snapshots.save_source is 'Event that triggered the snapshot: run_device, save_to_slot_*, chat_context, ai_replace, manual_save';

